@startmindmap sphinx_needs_data_explorer

'rankdir=LR nodesep=20

'skinparam nodesep 50%
'skinparam ranksep 50%
skinparam defaultFontSize 40%
skinparam DefaultTextAlignment center

/'
<style>
  mindmapDiagram {
  Scale 10
  LineColor Black
   node {
    FontName Roboto
    Padding 5
    Margin 15
   ' RoundCorner 11
    LineColor black
    BackgroundColor #cc33cc-#0c33ac
    FontColor white
    LineStyle 0
    LineThickness 1
    DiagonalCorner 50
    MinimumWidth 200
    MaximumWidth 200
  }
</style>
'/

<style>
  mindmapDiagram {
   node {
    Padding 30
    Margin 65
    'MinimumWidth 100
    MaximumWidth 00
  }
</style>

'top to bottom direction
'right to left direction
left to right direction
'scale 0.65
!$rootColor="#Orange"
!$Implemented="#Tomato"

!procedure $mcolor($arg1,$arg2)
<color:blue>[[ $arg1 $arg2 ]]</color>
!endprocedure

*[$rootColor] **sphinx_needs_data_explorer**
**[#lightgreen] **[[ https://www.sphinx-doc.org/en/master/ Sphinx ]]**
*** Sphinx Extension
****[#LightSkyBlue] Documentation
****[#LightSkyBlue] Automotive Requirement\nTraceability
****[#LightSkyBlue] Interactive Web-based\nAnalytical Tool
***** HTML
***** CSS
*****[#Yellow] JavaScript
****** [[ https://visjs.org visjs ]]
******* Dynamic and interactive\ndata network visualization
****** [[ https://github.com/peggyjs/peggy pegjs ]]
******* Powerful and flexible\nparser generator
****** [[ https://github.com/select2/select2 select2 ]]
******* Library for creating\nand managing user input
****** [[ https://github.com/jquery/jquery jQuery ]]
******* DOM manipulation library
****** [[ https://github.com/DataTables/DataTablesSrc DataTables ]]
******* HTML table enhancing library
****[#LightSkyBlue] Complement to **[[ https://www.sphinx-needs.com Sphinx-Needs ]]**
**[#lightgreen] **Open Source Project**\navailable in
*** [[ https://github.com/mi-parkes/sphinx-needs-data-explorer Github ]]
*** [[ https://pypi.org/project/sphinx-needs-data-explorer PYPI ]]
**[#lightgreen] **Platforms**
*** Linux
*** Mac OS X
*** Windows +10
**[#lightgreen] **Development Tools**
***[#LightSkyBlue] Package Management
**** poetry
***[#LightSkyBlue] IDE
**** VS Code
***** DevContainer
***[#LightSkyBlue]  CI/CD
**** GitHub Actions
***** Documentation
****** Generation
****** Deployment to GitHub Pages
@endmindmap
