name: CI with Reusable Python Workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

  #     - Init
  # pull_request:
  #   branches:
  #     - main

permissions:
  id-token: write
  pages: write

jobs:
  ci:
    uses: mi-parkes/custom-reusable-workflow/.github/workflows/ci-python.yml@main
    with:
      python-version: '3.12'
      coverage: false
      doc: true
